### ISSUE TITLE
Incorrect setup instructions.

### ISSUE THREAD

**Issue by godalming123** [Z-8Bit/Bspwm#1]
For instruction number 3 it uses the wrong script name:
```
chmod +X ./qtile-base-setup.sh
```
Also I'm pretty sure GitHub can remember file privileged so if you chmod then `git push` you do not have to include that step

**Comment by Z-8Bit** [comment]
ah my bad, I do know GH can remember file priveleges but I'd rather just tell the user to chmod it again.

**Comment by godalming123** [comment]
Ok closing I wouldn't say asking the user to chmod a file again is an issue
